# -*- coding: utf-8 -*-
"""Progetto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3woZTjxoFBrRKDvKcfE2Viq8awG_yPD
"""

import networkx as nx
from matplotlib import pyplot as plt, lines
import matplotlib

def degree(day):
    dict_degree = dict(nx.degree(day))
    max_degree = max(dict_degree.values())
    min_degree = min(dict_degree.values())
    average_degree = sum(dict_degree.values())/len(dict_degree)
    return [dict_degree, max_degree, min_degree, average_degree]

def bet(day):
    dict_betweeness = dict(nx.betweenness_centrality(day))
    max_betweeness = max(dict_betweeness.values())
    min_betweeness = min(dict_betweeness.values())
    average_betweeness = sum(dict_betweeness.values())/len(dict_betweeness)
    return [dict_betweeness, max_betweeness, min_betweeness, average_betweeness]

def eig(day):
    dict_eigen = dict(nx.eigenvector_centrality(day))
    max_eigen = max(dict_eigen.values())
    min_eigen = min(dict_eigen.values())
    average_eigen = sum(dict_eigen.values())/len(dict_eigen)
    return [dict_eigen, max_eigen, min_eigen, average_eigen]

def bridges(day):
    ponti=list(nx.bridges(day))
    return ponti

def densità(day):
  density = nx.density(day)
  density_percentuale = round(density * 100, 2)
  return [density, density_percentuale]

def connessione(day):
  return nx.is_connected(day)

def giorno(file_giorno):
  day = nx.read_edgelist(file_giorno, data = False)
  formiche = day.number_of_nodes()
  interazioni = day.number_of_edges()
  print(f'Il numero di formiche che hanno interagito il {file_giorno[7]} è stato: {formiche}')
  print(f'''
Il numero totale di interazioni tra formiche diverse è stato: {interazioni}
Vuol dire che sono avvenute il {densità(day)[1]}% di interazioni possibili tra due formiche diverse
  ''')

  if nx.is_connected(day):
    print('Non ci sono stati gruppi isolati di formiche')
  else:
    print('Ci sono stati gruppi isolati di formiche')

  return day

def istogramma(centrality, nome_centrality):
  plt.figure(figsize=(6, 7))

  plt.hist(centrality[0].values(),
           color = 'skyblue'
          )

  plt.axvline(x = centrality[3],
              color = 'r',
              linestyle = 'dashed', linewidth = 1
             )

  plt.title(f'Distribuzione della {nome_centrality.lower()}', color = 'red', weight = 'bold')
  plt.xlabel(f'{nome_centrality}')
  plt.ylabel('Frequenza')
  plt.show()

def Graph_bridges(G, giorno):
  ponti=bridges(G)
  non_ponti=[]
  for edge in G.edges():
    if frozenset(edge) not in ponti:
        non_ponti.append(edge)

  pos = nx.spring_layout(G, seed=42)
  plt.style.use('ggplot')
  fig = plt.figure(figsize=(15,15))
  ax = fig.add_subplot()

  nx.draw_networkx_nodes(G,
                           pos,
                           alpha = 0.67,
                           node_size = 500,
                           node_color= 'black'
                           )

  nx.draw_networkx_edges(G,
                           pos,
                           edgelist=ponti,
                           style = '-', edge_color = 'red', width=8
                           )
  nx.draw_networkx_edges(G,
                           pos,
                           edgelist=non_ponti,
                           style = '-', edge_color = 'blue', width=1
                           )

  nx.draw_networkx_labels(G,
                          pos,
                          font_size=10, font_color = 'white'
                          )

  fig.suptitle('PONTI DEL GRAFO',
                 fontstyle='italic',fontweight = 'normal', fontsize =25 , color = 'red'
                 )
  ax.set_title(giorno,
                 fontsize = 15, color = 'orange', fontweight = 'bold'
                 )
  plt.show()

def matrice(G, giorno):
    M = nx.adjacency_matrix(G)
    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot()

    fig.add_artist(lines.Line2D([0.13, 0.9], [0.88, 0.11]))
    ax.matshow(M.todense())

    fig.suptitle('Matrice di Adiacenza',
                 fontfamily='serif', fontweight='bold', fontsize=20, color='red')

    ax.set_title(giorno,
                 fontstyle='italic', fontsize=15, color='orange', fontweight='bold')

    plt.show()

def Graph_layout(G, giorno):
    fig, ax = plt.subplots(figsize=(15, 15))
    pos = nx.spring_layout(G, seed = 42)

    nx.draw_networkx_nodes(G,
                       pos,
                       alpha = 0.67 + 0.20,
                       node_size = 500, node_color='black'
                       )

    nx.draw_networkx_edges(G,
                       pos,
                       style = 'dashed', edge_color = 'salmon'
                       )

    nx.draw_networkx_labels(G,
                        pos,
                        font_size=10, font_color = 'white'
                        )


    fig.suptitle('COLONIA DI FORMICHE',
                 fontstyle='italic', fontweight='bold', fontsize=25, color='red')

    ax.set_title(giorno,
                 fontstyle='italic', fontsize=15, color='orange', fontweight='bold')
    plt.show()

def Graph_degree_centrality(G, giorno):
    pos = nx.spring_layout(G, seed=42)

    plt.style.use('ggplot')
    fig, ax = plt.subplots(figsize=(15,15))

    deg = degree(G)
    color_list = [deg[0][nodo] for nodo in G.nodes()]

    nx.draw_networkx_nodes(G,
                           pos,
                           ax=ax,
                           alpha=0.67,
                           node_size=500,
                           node_color=color_list,
                           cmap=plt.cm.Reds
                           )

    nx.draw_networkx_edges(G,
                           pos,
                           ax=ax,
                           style='-',
                           edge_color='gray'
                           )

    nx.draw_networkx_labels(G,
                            pos,
                            font_size=10,
                            font_color='black'
                            )

    fig.suptitle('DEGREE CENTRALITY',
                 fontstyle='italic',fontweight='bold', fontsize=20, color='red'
                 )

    ax.set_title(giorno,
                 fontstyle='italic',fontsize=15, color='orange', fontweight='bold'
                 )

    plt.show()

def Graph_betweness_centrality(G, giorno):
    pos = nx.spring_layout(G, seed=42)

    plt.style.use('ggplot')
    fig, ax = plt.subplots(figsize=(15,15))

    deg = bet(G)
    color_list = [deg[0][nodo] for nodo in G.nodes()]

    nx.draw_networkx_nodes(G,
                           pos,
                           ax=ax,
                           alpha=0.67,
                           node_size=500,
                           node_color=color_list,
                           cmap=plt.cm.Blues
                           )

    nx.draw_networkx_edges(G,
                           pos,
                           ax=ax,
                           style='-',
                           edge_color='gray'
                           )

    nx.draw_networkx_labels(G,
                            pos,
                            font_size=10,
                            font_color='black'
                            )

    fig.suptitle('BETWEENESS CENTRALITY',
                 fontstyle='italic',fontweight='bold', fontsize=20, color='red'
                 )

    ax.set_title(giorno,
                 fontstyle='italic',fontsize=15, color='orange', fontweight='bold'
                 )

    plt.show()

def Graph_eigenvector_centrality(G, giorno):
    pos = nx.spring_layout(G, seed=42)

    plt.style.use('ggplot')
    fig, ax = plt.subplots(figsize=(15,15))

    eigen = eig(G)
    color_list = [eigen[0][nodo] for nodo in G.nodes()]

    nx.draw_networkx_nodes(G,
                           pos,
                           ax=ax,
                           alpha=0.67,
                           node_size=500,
                           node_color=color_list,
                           cmap=plt.cm.viridis
                           )

    nx.draw_networkx_edges(G,
                           pos,
                           ax=ax,
                           style='-',
                           edge_color='gray'
                           )

    nx.draw_networkx_labels(G,
                            pos,
                            font_size=10,
                            font_color='black'
                            )

    fig.suptitle('EIGENVECTOR CENTRALITY',
                 fontstyle='italic',fontweight='bold', fontsize=20, color='red'
                 )

    ax.set_title(giorno,
                 fontstyle='italic',fontsize=15, color='orange', fontweight='bold'
                 )

    plt.show()

def community(G, comunità, giorno):
    com_color = []
    for formica in G.nodes():
        for com in comunità:
            if formica in com:
                com_color.append(comunità.index(com) / num_comunità)

    pos = nx.spring_layout(G, seed=42)
    plt.style.use('ggplot')
    fig = plt.figure(figsize=(15,15))
    ax = fig.add_subplot()

    nx.draw_networkx_nodes(G,
                           pos,
                           alpha = 0.67,
                           node_size = 500,
                           node_color= com_color,
                           cmap=plt.cm.tab20
                           )

    nx.draw_networkx_edges(G,
                           pos,
                           style = '-', edge_color = 'red'
                           )

    nx.draw_networkx_labels(G,
                            pos,
                            font_size=10, font_color = 'black'
                            )

    fig.suptitle('COMUNITÀ',
                 fontstyle='italic',fontweight = 'normal', fontsize = 25, color = 'red'
                 )
    ax.set_title(giorno,
                 fontsize = 15, color = 'orange', fontweight = 'bold'
                 )
    plt.show()

def gruppi_di_giornate(day1_included, day2_included, day3_included):
    combined_graph = nx.Graph()
    if day1_included:
        g1 = nx.read_edgelist('ant_day1.edges', data=False)
        combined_graph.add_nodes_from(g1.nodes())
        combined_graph.add_edges_from(g1.edges())
    if day2_included:
        g2 = nx.read_edgelist('ant_day2.edges', data=False)
        combined_graph.add_nodes_from(g2.nodes())
        combined_graph.add_edges_from(g2.edges())
    if day3_included:
        g3 = nx.read_edgelist('ant_day3.edges', data=False)
        combined_graph.add_nodes_from(g3.nodes())
        combined_graph.add_edges_from(g3.edges())
    return combined_graph

"""#**ANALISI DEL PRIMO GIORNO**"""

Day_1 = giorno('ant_day1.edges')

Graph_bridges(Day_1, 'Giorno 1')

Graph_layout(Day_1, 'Giorno 1')

matrice(Day_1, 'Giorno 1')

bet_1 = bet(Day_1)
deg_1 = degree(Day_1)
eig_1 = eig(Day_1)

Graph_degree_centrality(Day_1, 'Giorno 1')

istogramma(deg_1, 'Degree centrality')

Graph_betweness_centrality(Day_1, 'Giorno 1')

istogramma(bet_1, 'Betweenness centrality')

Graph_eigenvector_centrality(Day_1, 'Giorno 1')

istogramma(eig_1, 'Eigenvector centrality')

#Conclusioni su degree, betweenness e eigenvector centrality
def analisi(centrality):
  ma = [k
        for k, v in centrality[0].items()
        if v == centrality[1]
       ]
  mi = [k
           for k, v in centrality[0].items()
           if v == centrality[2]
           ]
  return [ma, mi]

estremi_deg_1 = analisi(deg_1)
print('DEGREE CENTRALITY:')
if len(estremi_deg_1[0]) > 1:
  print(f'Le formiche che hanno comunicato con più formiche (degree massima) sono state: {estremi_deg_1[0]}')
else:
  print(f'La formica che ha comunicato con più formiche (degree massima) è stata: {estremi_deg_1[0]}')
print(f'Comunicando con {deg_1[1]} altre formiche')

if len(estremi_deg_1[1]) > 1:
  print(f'Invece quelle che hanno comunicato con il minor numero di formiche (degree minima) sono state: {estremi_deg_1[1]}')
else:
  print(f'Invece quella che ha comunicato con il minor numero di formiche (degree minima) è stata: {estremi_deg_1[1]}')
print(f'Comunicando solo con {deg_1[2]}')
print(f'Ogni formica ha comunicato mediamente con {round(deg_1[3], 2)} formiche\n')


estremi_bet_1 = analisi(bet_1)
print('BETWEENNESS CENTRALITY:')
if len(estremi_bet_1[0]) > 1:
  print(f'Le formiche più importanti per le comunicazioni (betweenness massima) sono state: {estremi_bet_1[0]}')
else:
  print(f'La formica più importante per le comunicazioni (betweenness massima) è stata: {estremi_bet_1[0]}')
print(f'Con un valore di betweenness di: {round(bet_1[1], 2)}')

if len(estremi_bet_1[1]) > 1:
  print(f'Invece quelle più irrilevanti (betweenness minima) sono state: {estremi_bet_1[1]}')
else:
  print(f'Invece quella più irrilevante (betweenness minima) è stata: {estremi_bet_1[1]}')
print(f'Con un valore di betweenness di: {bet_1[2]}')
print(f'Ogni formica ha un valore di betweenness medio di: {round(bet_1[3], 2)}\n')



estremi_eig_1 = analisi(eig_1)
print('EIGENVECTOR CENTRALITY:')
if len(estremi_eig_1[0]) > 1:
  print(f'Le formiche vicine a più formiche influenti (eigenvector centrality massima) sono state: {estremi_eig_1[0]}')
else:
  print(f'La formica vicina a più formiche influenti (eigenvector centrality massima) è stata: {estremi_eig_1[0]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_1[1], 2)}')

if len(estremi_eig_1[1]) > 1:
  print(f'Invece quelle vicine a formiche meno influenti (eigenvector centrality minima) sono state: {estremi_eig_1[1]}')
else:
  print(f'Invece quella vicina a formiche meno influenti (betweigenvector centralityeenness minima) è stata: {estremi_eig_1[1]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_1[2], 2)}\n\n')


importanza = []
for i in Day_1.nodes():
  k = 0

  if i in estremi_bet_1[0]:
    k += 1
  elif i in estremi_bet_1[1]:
    k -= 1
  else:
    pass

  if i in estremi_eig_1[0]:
    k += 1
  elif i in estremi_eig_1[1]:
    k -= 1
  else:
    pass

  if i in estremi_deg_1[0]:
    k += 1
  elif i in estremi_deg_1[1]:
    k -= 1
  importanza.append(k)

importanti = [i + 1
              for i in range(len(importanza))
              if importanza[i] == max(importanza)
             ]
if len(importanti) > 1:
  print(f'I nodi più importanti sono stati: {importanti}')
else:
  print(f'Il nodo più importante è stato: {importanti}')

non_importanti = [i + 1
                  for i in range(len(importanza))
                  if importanza[i] == min(importanza)
                  ]
if len(non_importanti) > 1:
  print(f'I nodi meno importanti sono stati: {non_importanti}')
else:
  print(f'Il nodo meno importante è stato: {non_importanti}')

comunità = list(nx.community.greedy_modularity_communities(Day_1))
num_comunità = len(comunità)
print(f'Le formiche si sono divise in {num_comunità} comunità')

community(Day_1, comunità, 'Giorno 1')

"""#**ANALISI DEL SECONDO GIORNO**"""

Day_2 = giorno('ant_day2.edges')

Graph_bridges(Day_2, 'Giorno 2')

Graph_layout(Day_2, 'Giorno 2')

matrice(Day_2, 'Giorno 2')

bet_2 = bet(Day_2)
deg_2 = degree(Day_2)
eig_2 = eig(Day_2)

Graph_degree_centrality(Day_2, 'Giorno 2')

istogramma(deg_2, 'Degree centrality')

Graph_betweness_centrality(Day_2, 'Giorno 2')

istogramma(bet_2, 'Betweenness centrality')

Graph_eigenvector_centrality(Day_2, 'Giorno 2')

istogramma(eig_2, 'Eigenvector centrality')

#Conclusioni su degree, betweenness e eigenvector centrality
def analisi(centrality):
  ma = [k
        for k, v in centrality[0].items()
        if v == centrality[1]
       ]
  mi = [k
           for k, v in centrality[0].items()
           if v == centrality[2]
           ]
  return [ma, mi]

estremi_deg_2 = analisi(deg_2)
print('DEGREE CENTRALITY:')
if len(estremi_deg_2[0]) > 1:
  print(f'Le formiche che hanno comunicato con più formiche (degree massima) sono state: {estremi_deg_2[0]}')
else:
  print(f'La formica che ha comunicato con più formiche (degree massima) è stata: {estremi_deg_2[0]}')
print(f'Comunicando con {deg_2[1]} altre formiche')

if len(estremi_deg_2[1]) > 1:
  print(f'Invece quelle che hanno comunicato con il minor numero di formiche (degree minima) sono state: {estremi_deg_2[1]}')
else:
  print(f'Invece quella che ha comunicato con il minor numero di formiche (degree minima) è stata: {estremi_deg_2[1]}')
print(f'Comunicando solo con {deg_2[2]}')
print(f'Ogni formica ha comunicato mediamente con {round(deg_2[3], 2)} formiche\n')


estremi_bet_2 = analisi(bet_2)
print('BETWEENNESS CENTRALITY:')
if len(estremi_bet_2[0]) > 1:
  print(f'Le formiche più importanti per le comunicazioni (betweenness massima) sono state: {estremi_bet_2[0]}')
else:
  print(f'La formica più importante per le comunicazioni (betweenness massima) è stata: {estremi_bet_2[0]}')
print(f'Con un valore di betweenness di: {round(bet_2[1], 2)}')

if len(estremi_bet_2[1]) > 1:
  print(f'Invece quelle più irrilevanti (betweenness minima) sono state: {estremi_bet_2[1]}')
else:
  print(f'Invece quella più irrilevante (betweenness minima) è stata: {estremi_bet_2[1]}')
print(f'Con un valore di betweenness di: {bet_2[2]}')
print(f'Ogni formica ha un valore di betweenness medio di: {round(bet_2[3], 2)}\n')



estremi_eig_2 = analisi(eig_2)
print('EIGENVECTOR CENTRALITY:')
if len(estremi_eig_2[0]) > 1:
  print(f'Le formiche vicine a più formiche influenti (eigenvector centrality massima) sono state: {estremi_eig_2[0]}')
else:
  print(f'La formica vicina a più formiche influenti (eigenvector centrality massima) è stata: {estremi_eig_2[0]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_2[1], 2)}')

if len(estremi_eig_2[1]) > 1:
  print(f'Invece quelle vicine a formiche meno influenti (eigenvector centrality minima) sono state: {estremi_eig_2[1]}')
else:
  print(f'Invece quella vicina a formiche meno influenti (betweigenvector centralityeenness minima) è stata: {estremi_eig_2[1]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_2[2], 2)}\n\n')


importanza = []
for i in Day_2.nodes():
  k = 0

  if i in estremi_bet_2[0]:
    k += 1
  elif i in estremi_bet_2[1]:
    k -= 1
  else:
    pass

  if i in estremi_eig_2[0]:
    k += 1
  elif i in estremi_eig_2[1]:
    k -= 1
  else:
    pass

  if i in estremi_deg_2[0]:
    k += 1
  elif i in estremi_deg_2[1]:
    k -= 1
  importanza.append(k)

importanti = [i + 1
              for i in range(len(importanza))
              if importanza[i] == max(importanza)
             ]
if len(importanti) > 1:
  print(f'I nodi più importanti sono stati: {importanti}')
else:
  print(f'Il nodo più importante è stato: {importanti}')

non_importanti = [i + 1
                  for i in range(len(importanza))
                  if importanza[i] == min(importanza)
                  ]
if len(non_importanti) > 1:
  print(f'I nodi meno importanti sono stati: {non_importanti}')
else:
  print(f'Il nodo meno importante è stato: {non_importanti}')

comunità = list(nx.community.greedy_modularity_communities(Day_2))
num_comunità = len(comunità)
print(f'Le formiche si sono divise in {num_comunità} comunità')

community(Day_2, comunità, 'Giorno 2')

"""#**ANALISI DEL TERZO GIORNO**"""

Day_3 = giorno('ant_day3.edges')

Graph_bridges(Day_3, 'Giorno 3')

Graph_layout(Day_3, 'Giorno 3')

matrice(Day_3, 'Giorno 3')

bet_3 = bet(Day_3)
deg_3 = degree(Day_3)
eig_3 = eig(Day_3)

Graph_degree_centrality(Day_3, 'Giorno 3')

istogramma(deg_3, 'Degree centrality')

Graph_betweness_centrality(Day_3, 'Giorno 3')

istogramma(bet_3, 'Betweenness centrality')

Graph_eigenvector_centrality(Day_3, 'Giorno 3')

istogramma(eig_3, 'Eigenvector centrality')

#Conclusioni su degree, betweenness e eigenvector centrality
def analisi(centrality):
  ma = [k
        for k, v in centrality[0].items()
        if v == centrality[1]
       ]
  mi = [k
           for k, v in centrality[0].items()
           if v == centrality[2]
           ]
  return [ma, mi]

estremi_deg_3 = analisi(deg_3)
print('DEGREE CENTRALITY:')
if len(estremi_deg_3[0]) > 1:
  print(f'Le formiche che hanno comunicato con più formiche (degree massima) sono state: {estremi_deg_3[0]}')
else:
  print(f'La formica che ha comunicato con più formiche (degree massima) è stata: {estremi_deg_3[0]}')
print(f'Comunicando con {deg_3[1]} altre formiche')

if len(estremi_deg_3[1]) > 1:
  print(f'Invece quelle che hanno comunicato con il minor numero di formiche (degree minima) sono state: {estremi_deg_3[1]}')
else:
  print(f'Invece quella che ha comunicato con il minor numero di formiche (degree minima) è stata: {estremi_deg_3[1]}')
print(f'Comunicando solo con {deg_3[2]}')
print(f'Ogni formica ha comunicato mediamente con {round(deg_3[3], 2)} formiche\n')


estremi_bet_3 = analisi(bet_3)
print('BETWEENNESS CENTRALITY:')
if len(estremi_bet_3[0]) > 1:
  print(f'Le formiche più importanti per le comunicazioni (betweenness massima) sono state: {estremi_bet_3[0]}')
else:
  print(f'La formica più importante per le comunicazioni (betweenness massima) è stata: {estremi_bet_3[0]}')
print(f'Con un valore di betweenness di: {round(bet_3[1], 2)}')

if len(estremi_bet_3[1]) > 1:
  print(f'Invece quelle più irrilevanti (betweenness minima) sono state: {estremi_bet_3[1]}')
else:
  print(f'Invece quella più irrilevante (betweenness minima) è stata: {estremi_bet_3[1]}')
print(f'Con un valore di betweenness di: {bet_3[2]}')
print(f'Ogni formica ha un valore di betweenness medio di: {round(bet_3[3], 2)}\n')



estremi_eig_3 = analisi(eig_3)
print('EIGENVECTOR CENTRALITY:')
if len(estremi_eig_3[0]) > 1:
  print(f'Le formiche vicine a più formiche influenti (eigenvector centrality massima) sono state: {estremi_eig_3[0]}')
else:
  print(f'La formica vicina a più formiche influenti (eigenvector centrality massima) è stata: {estremi_eig_3[0]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_3[1], 2)}')

if len(estremi_eig_3[1]) > 1:
  print(f'Invece quelle vicine a formiche meno influenti (eigenvector centrality minima) sono state: {estremi_eig_3[1]}')
else:
  print(f'Invece quella vicina a formiche meno influenti (betweigenvector centralityeenness minima) è stata: {estremi_eig_3[1]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_3[2], 2)}\n\n')


importanza = []
for i in Day_3.nodes():
  k = 0

  if i in estremi_bet_3[0]:
    k += 1
  elif i in estremi_bet_3[1]:
    k -= 1
  else:
    pass

  if i in estremi_eig_3[0]:
    k += 1
  elif i in estremi_eig_3[1]:
    k -= 1
  else:
    pass

  if i in estremi_deg_3[0]:
    k += 1
  elif i in estremi_deg_3[1]:
    k -= 1
  importanza.append(k)

importanti = [i + 1
              for i in range(len(importanza))
              if importanza[i] == max(importanza)
             ]
if len(importanti) > 1:
  print(f'I nodi più importanti sono stati: {importanti}')
else:
  print(f'Il nodo più importante è stato: {importanti}')

non_importanti = [i + 1
                  for i in range(len(importanza))
                  if importanza[i] == min(importanza)
                  ]
if len(non_importanti) > 1:
  print(f'I nodi meno importanti sono stati: {non_importanti}')
else:
  print(f'Il nodo meno importante è stato: {non_importanti}')

comunità = list(nx.community.greedy_modularity_communities(Day_3))
num_comunità = len(comunità)
print(f'Le formiche si sono divise in {num_comunità} comunità')

community(Day_3, comunità, 'Giorno 3')

"""#**GIORNATE INSIEME**"""

while True:
  print('Quali giornate (1, 2, 3) vuoi visualizzare unite? (es. giornate 1 e 3: 1,3)')
  giornate = input()
  var = [s.strip() for s in giornate.split(',')]

  if len(var) >= 2 and len(var) <= 3 and all(day in ['1', '2', '3'] for day in var):
    giorni_list = []
    if '1' in var:
      giorni_list.append('1')
    if '2' in var:
      giorni_list.append('2')
    if '3' in var:
      giorni_list.append('3')

    if len(giorni_list) == 2:
      giorni = f'Giorni {giorni_list[0]} e {giorni_list[1]}'
    elif len(giorni_list) == 3:
      giorni = f'Giorni {giorni_list[0]}, {giorni_list[1]} e {giorni_list[2]}'
    else:
      giorni = f'Giorni {", ".join(giorni_list)}'
    break
  else:
    print('Errore: vanno digitate almeno due e al massimo tre giornate valide (1, 2, 3), separate da virgole.')

x = '1' in var
y = '2' in var
z = '3' in var

Days = gruppi_di_giornate(x, y, z)

formiche = Days.number_of_nodes()
interazioni = Days.number_of_edges()
print(f'Il numero di formiche che hanno interagito i giorni  è stato: {formiche}')
print(f'''
Il numero totale di interazioni tra formiche diverse è stato: {interazioni}
Vuol dire che sono avvenute il {densità(Days)[1]}% di interazioni possibili tra due formiche diverse
  ''')

if nx.is_connected(Days):
  print('Non ci sono stati gruppi isolati di formiche')
else:
  print('Ci sono stati gruppi isolati di formiche')

Graph_bridges(Days, giorni)

Graph_layout(Days, giorni)

matrice(Days, giorni)

bet_s = bet(Days)
deg_s = degree(Days)
eig_s = eig(Days)

Graph_degree_centrality(Days, giorni)

istogramma(deg_s, 'Degree centrality')

Graph_betweness_centrality(Days, giorni)

istogramma(bet_s, 'Betweenness centrality')

Graph_eigenvector_centrality(Days, giorni)

istogramma(eig_s, 'Eigenvector centrality')

#Conclusioni su degree, betweenness e eigenvector centrality
def analisi(centrality):
  ma = [k
        for k, v in centrality[0].items()
        if v == centrality[1]
       ]
  mi = [k
           for k, v in centrality[0].items()
           if v == centrality[2]
           ]
  return [ma, mi]

estremi_deg_s = analisi(deg_s)
print('DEGREE CENTRALITY:')
if len(estremi_deg_s[0]) > 1:
  print(f'Le formiche che hanno comunicato con più formiche (degree massima) sono state: {estremi_deg_s[0]}')
else:
  print(f'La formica che ha comunicato con più formiche (degree massima) è stata: {estremi_deg_s[0]}')
print(f'Comunicando con {deg_s[1]} altre formiche')

if len(estremi_deg_s[1]) > 1:
  print(f'Invece quelle che hanno comunicato con il minor numero di formiche (degree minima) sono state: {estremi_deg_s[1]}')
else:
  print(f'Invece quella che ha comunicato con il minor numero di formiche (degree minima) è stata: {estremi_deg_s[1]}')
print(f'Comunicando solo con {deg_s[2]}')
print(f'Ogni formica ha comunicato mediamente con {round(deg_s[3], 2)} formiche\n')


estremi_bet_s = analisi(bet_s)
print('BETWEENNESS CENTRALITY:')
if len(estremi_bet_s[0]) > 1:
  print(f'Le formiche più importanti per le comunicazioni (betweenness massima) sono state: {estremi_bet_s[0]}')
else:
  print(f'La formica più importante per le comunicazioni (betweenness massima) è stata: {estremi_bet_s[0]}')
print(f'Con un valore di betweenness di: {round(bet_s[1], 2)}')

if len(estremi_bet_s[1]) > 1:
  print(f'Invece quelle più irrilevanti (betweenness minima) sono state: {estremi_bet_s[1]}')
else:
  print(f'Invece quella più irrilevante (betweenness minima) è stata: {estremi_bet_s[1]}')
print(f'Con un valore di betweenness di: {bet_s[2]}')
print(f'Ogni formica ha un valore di betweenness medio di: {round(bet_s[3], 2)}\n')



estremi_eig_s = analisi(eig_s)
print('EIGENVECTOR CENTRALITY:')
if len(estremi_eig_s[0]) > 1:
  print(f'Le formiche vicine a più formiche influenti (eigenvector centrality massima) sono state: {estremi_eig_s[0]}')
else:
  print(f'La formica vicina a più formiche influenti (eigenvector centrality massima) è stata: {estremi_eig_s[0]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_s[1], 2)}')

if len(estremi_eig_s[1]) > 1:
  print(f'Invece quelle vicine a formiche meno influenti (eigenvector centrality minima) sono state: {estremi_eig_s[1]}')
else:
  print(f'Invece quella vicina a formiche meno influenti (betweigenvector centralityeenness minima) è stata: {estremi_eig_s[1]}')
print(f'Con un valore di eigenvector centrality di: {round(eig_s[2], 2)}\n\n')


importanza = []
for i in Days.nodes():
  k = 0

  if i in estremi_bet_s[0]:
    k += 1
  elif i in estremi_bet_s[1]:
    k -= 1
  else:
    pass

  if i in estremi_eig_s[0]:
    k += 1
  elif i in estremi_eig_s[1]:
    k -= 1
  else:
    pass

  if i in estremi_deg_s[0]:
    k += 1
  elif i in estremi_deg_s[1]:
    k -= 1
  importanza.append(k)

importanti = [i + 1
              for i in range(len(importanza))
              if importanza[i] == max(importanza)
             ]
if len(importanti) > 1:
  print(f'I nodi più importanti sono stati: {importanti}')
else:
  print(f'Il nodo più importante è stato: {importanti}')

non_importanti = [i + 1
                  for i in range(len(importanza))
                  if importanza[i] == min(importanza)
                  ]
if len(non_importanti) > 1:
  print(f'I nodi meno importanti sono stati: {non_importanti}')
else:
  print(f'Il nodo meno importante è stato: {non_importanti}')

comunità = list(nx.community.greedy_modularity_communities(Days))
num_comunità = len(comunità)
print(f'Le formiche si sono divise in {num_comunità} comunità')

community(Days, comunità, giorni)